// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240707161627_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Entities.GetDetail", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("GetDetails");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.LoginForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginForms");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.MouldingData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AirBlowOff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CavityNumberStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChamberGapRamSwing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChamberHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChillPlacing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreSeating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateCodeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilterPlacing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoundryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImprovementTrial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LaddleDelayMetalDistribution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LooseSand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeltMaintDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeltingDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoldMaintDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldBreakageStatusRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldBreakageStatusSwing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldBrokenQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldCrush")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldHardnessRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldHardnessSwing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldingMachine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldsMadeActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldsMadePlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldsPouredActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouldsPouredPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NPTTrials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfCavities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfMouldsTakeOutDueToLeak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPChangeDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumberStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatternRelatedProblem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SprayNozzleCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartUpDelay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopperRodPlungerRodIssues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TundishChangeNozzleChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualCastingInspection")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MouldingData");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.Test", b =>
                {
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("WebApplication1.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
